export { Ring } from './Ring'
export { RedSquare } from './RedSquare'
export { Circle } from './Circle'
export { PinkSquare } from './PinkSquare'
export { BlueTriangle } from './BlueTriangle'
export { Star } from './Star'
export { TrianglePlay } from './TrianglePlay'
export { Loading } from './Loading'