export * from './LoginForm/ui/index'
export * from './RegistrationForm/ui/index'
export * from './RecoveryForm/ui/index'
export * from './NewPasswordForm/ui/index'
export * from './StatisticInfo/ui/index'